#!/command/with-contenv bash

# OpenSSH Server configuration
#
echo "🤖 Setting SSH configuration..."
{
  echo "Host *"
  echo "  ForwardAgent ${SSH_FORWARD_AGENT:-no}"
  echo "  StrictHostKeyChecking ${SSH_STRICT_HOSTKEY_CHECKING:-no}"
} > /etc/ssh/ssh_config.d/ssh_utils.conf
