#!/command/with-contenv bash

DHOME="${DHOME:-"/home/$DUSER"}"

# Configure SSH user
groupmod -g ${DGID} -n ${DGROUP} ssh-user
usermod -u ${DUID} -g ${DGID} --login ${DUSER} --move-home --home ${DHOME} ssh-user
mkdir -p ${DHOME}
chown -R ${DUSER}:${DGROUP} ${DHOME}
chown -R ${DUSER}:${DGROUP} ${DHOME}/.[^.]*

echo "
-------------------------------------
👨 Running Services as User: $DUSER
-------------------------------------
"
