#!/command/with-contenv bash
# shellcheck shell=bash

declare -x SSH_AGENT_ENABLED="${SSH_AGENT_ENABLED:-false}"
declare -x SSH_ADD_WATCHER_ENABLED="${SSH_ADD_WATCHER_ENABLED:-false}"
declare -x SSHD_ENABLED="${SSHD_ENABLED,:-true}"
declare _enabled=✅
declare _disabled=🚫
declare _sep="---------------------------------------------------"
declare outputFormat="%-20s  |  %-10s\n"


# print logo
cat /etc/motd
#################################
printf "%s\n" $_sep
printf "$outputFormat" Service Enabled
printf "%s\n" $_sep

if [[ "${SSH_AGENT_ENABLED,,}" == "true" ]]
  then
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/ssh-agent
    printf "$outputFormat" SSH-AGENT $_enabled
  else
    printf "$outputFormat" SSH-AGENT $_disabled
fi

if [[ "${SSH_ADD_WATCHER_ENABLED,,}" == "true" ]]
  then
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/ssh-add-watcher
    printf "$outputFormat" "SSH-ADD Watcher" $_enabled
  else
    printf "$outputFormat" "SSH-ADD Watcher" $_disabled

fi

if [[ "${SSHD_ENABLED,,}" == "true" ]]
  then
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/openssh-server
    printf "$outputFormat" SSHD $_enabled
  else
    printf "$outputFormat" SSHD $_disabled
fi

printf "%s\n" $_sep
#################################################################
