#!/command/with-contenv bash

echo "🚀 Starting SSHD..."
echo "🛡 SSHD PAM: ${SSH_PASSWORD_AUTH}"
if [[ "${SSH_PASSWORD_AUTH}" == "yes" ]]
then
  s6-setuidgid "${DUSER}" /usr/sbin/sshd.pam -D -e
else
  s6-setuidgid "${DUSER}" /usr/sbin/sshd -D -e
fi
